version: '3'
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - .:/css-battle-fe
    environment:
      - API_KEY=AIzaSyA8HC-ThMxX131sgcwKelEniyLvBndvSXk
      - AUTH_DOMAIN=css-battle-clone.firebaseapp.com
      - PROJECT_ID=css-battle-clone
      - STORAGE_BUCKET=css-battle-clone.appspot.com
      - MESSAGING_SENDER_ID=964995637410
      - APP_ID=1:964995637410:web:c0076aa62114899a64b7fb
      - MEASUREMENT_ID=G-2MB9SGQHS3
      - REACT_APP_API_BASE_URL=back-end:8080
    ports:
      - 5173:5173
    command: yarn dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - back-end
    networks:
      - css-battle

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - .:/css-battle-be
    environment:
      - MAIL_USERNAME=buiduclong0511@gmail.com
      - MAIL_PASSWORD=bcmtmqngcciewowk
      - DB_DIALECT=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root@123
      - DB_DATABASE_NAME=css_battle_clone
      - JWT_TTL=3600
      - JWT_SECRET=shh
    ports:
      - 8080:8080
    command: yarn migrate && yarn dev
    depends_on:
      - db
    networks:
      - css-battle
  
  db:
    image: mysql:8.2.0
    ports:
      - 3306:3306
    volumes:
      - css-battle-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
      - MYSQL_DATABASE=css_battle_clone
    networks:
      - css-battle
    
networks:
  css-battle:
    driver: bridge
volumes:
  css-battle-data: